using Blackbird.Applications.Sdk.Common.Dynamic;
using Blackbird.Applications.Sdk.Common.Dictionaries;

namespace Apps.Pantheon.Handlers.Static;

public class LanguageDataHandler : IStaticDataSourceItemHandler
{
    public IEnumerable<DataSourceItem> GetData()
    {
        return new List<DataSourceItem>
        {
            new DataSourceItem("01-GO", "Hinglish (Google ONLY) - India"),
            new DataSourceItem("FR-GF", "French - French Guiana"),
            new DataSourceItem("Haka-IN", "Hakha Chin - India"),
            new DataSourceItem("LeetSp-All", "Leetspeak - All"),
            new DataSourceItem("aa-ET", "Afar - Ethiopia"),
            new DataSourceItem("abk-GE", "Abkhazian - Georgia"),
            new DataSourceItem("af-NA", "Afrikaans - Namibia"),
            new DataSourceItem("af-ZA", "Afrikaans - South Africa"),
            new DataSourceItem("ak-GH", "Akan - Ghana"),
            new DataSourceItem("am-ET", "Amharic - Ethiopia"),
            new DataSourceItem("apd-SDL", "Arabic - Sudan, Latin"),
            new DataSourceItem("ar-AE", "Arabic - United Arab Emirates"),
            new DataSourceItem("ar-AllC", "Arabic - All countries"),
            new DataSourceItem("ar-BH", "Arabic - Bahrain"),
            new DataSourceItem("ar-DZ", "Arabic - Algeria"),
            new DataSourceItem("ar-EG", "Arabic - Egypt"),
            new DataSourceItem("ar-EH", "Arabic - Western Sahara"),
            new DataSourceItem("ar-IQ", "Arabic - Iraq"),
            new DataSourceItem("ar-JO", "Arabic - Jordan"),
            new DataSourceItem("ar-KW", "Arabic - Kuwait"),
            new DataSourceItem("ar-LB", "Arabic - Lebanon"),
            new DataSourceItem("ar-LY", "Arabic - Libya"),
            new DataSourceItem("ar-MA", "Arabic - Morocco"),
            new DataSourceItem("ar-MR", "Arabic - Mauritania"),
            new DataSourceItem("ar-MidE", "Arabic - Middle East"),
            new DataSourceItem("ar-Nafr", "Arabic - Northern Africa"),
            new DataSourceItem("ar-OM", "Arabic - Oman"),
            new DataSourceItem("ar-PS", "Arabic - West Bank"),
            new DataSourceItem("ar-QA", "Arabic - Qatar"),
            new DataSourceItem("ar-SA", "Arabic - Saudi Arabia"),
            new DataSourceItem("ar-SD", "Arabic - Sudan"),
            new DataSourceItem("ar-SY", "Arabic - Syrian Arab Republic"),
            new DataSourceItem("ar-TD", "Arabic - Chad"),
            new DataSourceItem("ar-TN", "Arabic - Tunisia"),
            new DataSourceItem("ar-YE", "Arabic - Yemen"),
            new DataSourceItem("arn-CL", "Mapudungun - Chile"),
            new DataSourceItem("as-IN", "Assamese - India"),
            new DataSourceItem("ast-ES", "Asturian - Spain"),
            new DataSourceItem("az-Cyrl-AZ", "Azeri - Azerbaijan"),
            new DataSourceItem("az-Latn-AZ", "Azeri - Azerbaijan"),
            new DataSourceItem("aze-AZ", "Azerbaijani - Azerbaijan"),
            new DataSourceItem("ba-ML", "Bamanankan - Mali"),
            new DataSourceItem("ba-RU", "Bashkir - Russian Federation"),
            new DataSourceItem("ban-Bali", "Balinese - Bali"),
            new DataSourceItem("be-BY", "Belarusian - Belarus"),
            new DataSourceItem("bg-BG", "Bulgarian - Bulgaria"),
            new DataSourceItem("bgc-IN", "Haryanvi - India"),
            new DataSourceItem("bho-IN", "Bhojpuri - India"),
            new DataSourceItem("bn-BD", "Bengali - Bangladesh"),
            new DataSourceItem("bn-IN", "Bengali - India"),
            new DataSourceItem("bo-CN", "Tibetan Standard - China"),
            new DataSourceItem("br-FR", "Breton - France"),
            new DataSourceItem("bs-Cyrl-BA", "Bosnian - Bosnia and Herzegovina"),
            new DataSourceItem("bs-Latn-BA", "Bosnian - Bosnia and Herzegovina"),
            new DataSourceItem("btk-ID", "Toba Batak - Indonesia"),
            new DataSourceItem("bwu-GH", "Buli - Ghana"),
            new DataSourceItem("ca-ES", "Catalan - Spain"),
            new DataSourceItem("cal-FM", "Carolinian - Micronesia"),
            new DataSourceItem("ceb-PH", "Cebuano - Philippines"),
            new DataSourceItem("ch-GU", "Chamorro - Guam"),
            new DataSourceItem("chr-US", "Cherokee - United States"),
            new DataSourceItem("co-FR", "Corsican - France"),
            new DataSourceItem("cpe-US", "Creole - USA"),
            new DataSourceItem("crs-SYC", "Creole - Seychelles"),
            new DataSourceItem("cs-CZ", "Czech - Czech Republic"),
            new DataSourceItem("cy-GB", "Welsh - United Kingdom"),
            new DataSourceItem("da-DK", "Danish - Denmark"),
            new DataSourceItem("de-AT", "German - Austria"),
            new DataSourceItem("de-BE", "German - Belgium"),
            new DataSourceItem("de-CH", "German - Switzerland"),
            new DataSourceItem("de-DE", "German - Germany"),
            new DataSourceItem("de-LI", "German - Liechtenstein"),
            new DataSourceItem("de-LU", "German - Luxembourg"),
            new DataSourceItem("de-NL", "German - Holland"),
            new DataSourceItem("di-SS", "Dinka - South Sudan"),
            new DataSourceItem("div-MV", "Divehi - Maldives"),
            new DataSourceItem("dtk-GOT", "Dothraki - GoT"),
            new DataSourceItem("dz-BT", "Dzongkha - Bhutan"),
            new DataSourceItem("ee-GH", "Ewe - Ghana"),
            new DataSourceItem("el-CY", "Greek - Cyprus"),
            new DataSourceItem("el-GR", "Greek - Greece"),
            new DataSourceItem("en-AE", "English - UAE, Dubai"),
            new DataSourceItem("en-AT", "English - Austria"),
            new DataSourceItem("en-AU", "English - Australia"),
            new DataSourceItem("en-AUes", "English - Australia East"),
            new DataSourceItem("en-AUws", "English - Australia West"),
            new DataSourceItem("en-Asia", "English - Asia"),
            new DataSourceItem("en-BS", "English - Bahamas"),
            new DataSourceItem("en-BZ", "English - Belize"),
            new DataSourceItem("en-CA", "English - Canada"),
            new DataSourceItem("en-CH", "English - Switzerland"),
            new DataSourceItem("en-CN", "English - China"),
            new DataSourceItem("en-CY", "English - Cyprus"),
            new DataSourceItem("en-DE", "English - Germany"),
            new DataSourceItem("en-EG", "English - Egypt"),
            new DataSourceItem("en-GB", "English - United Kingdom"),
            new DataSourceItem("en-HK", "English - Hong Kong"),
            new DataSourceItem("en-ID", "English - Indonesia"),
            new DataSourceItem("en-IE", "English - Ireland"),
            new DataSourceItem("en-IN", "English - India"),
            new DataSourceItem("en-INT", "English - International"),
            new DataSourceItem("en-JM", "English - Jamaica"),
            new DataSourceItem("en-JO", "English - Jordan"),
            new DataSourceItem("en-JP", "English - Japan"),
            new DataSourceItem("en-KE", "English - Kenya"),
            new DataSourceItem("en-KR", "English - Korea"),
            new DataSourceItem("en-KW", "English - Kuwait"),
            new DataSourceItem("en-MY", "English - Malaysia"),
            new DataSourceItem("en-NL", "English - Netherlands"),
            new DataSourceItem("en-NO", "English - Norway"),
            new DataSourceItem("en-NZ", "English - New Zealand"),
            new DataSourceItem("en-PH", "English - Philippines"),
            new DataSourceItem("en-QA", "English - Qatar"),
            new DataSourceItem("en-SA", "English - Saudi Arabia"),
            new DataSourceItem("en-SG", "English - Singapore"),
            new DataSourceItem("en-TH", "English - Thailand"),
            new DataSourceItem("en-TT", "English - Trinidad and Tobago"),
            new DataSourceItem("en-UG", "English - Uganda"),
            new DataSourceItem("en-US", "English - United States"),
            new DataSourceItem("en-ZA", "English - South Africa"),
            new DataSourceItem("en-ZW", "English - Zimbabwe"),
            new DataSourceItem("eo-Intl", "Esperanto - International"),
            new DataSourceItem("es-AR", "Spanish - Argentina"),
            new DataSourceItem("es-Andes", "Spanish - Andean"),
            new DataSourceItem("es-BO", "Spanish - Bolivia, Plurinational State of"),
            new DataSourceItem("es-CL", "Spanish - Chile"),
            new DataSourceItem("es-CO", "Spanish - Colombia"),
            new DataSourceItem("es-CR", "Spanish - Costa Rica"),
            new DataSourceItem("es-CU", "Spanish - Cuba"),
            new DataSourceItem("es-CentAm", "Spanish - Central America"),
            new DataSourceItem("es-DO", "Spanish - Dominican Republic"),
            new DataSourceItem("es-ES", "Spanish - Spain"),
            new DataSourceItem("es-GT", "Spanish - Guatemala"),
            new DataSourceItem("es-HN", "Spanish - Honduras"),
            new DataSourceItem("es-Intl", "Spanish - International"),
            new DataSourceItem("es-LatAm", "Spanish - Latin America"),
            new DataSourceItem("es-MX", "Spanish - Mexico"),
            new DataSourceItem("es-NI", "Spanish - Nicaragua"),
            new DataSourceItem("es-PA", "Spanish - Panama"),
            new DataSourceItem("es-PE", "Spanish - Peru"),
            new DataSourceItem("es-PR", "Spanish - Puerto Rico"),
            new DataSourceItem("es-PY", "Spanish - Paraguay"),
            new DataSourceItem("es-SV", "Spanish - El Salvador"),
            new DataSourceItem("es-US", "Spanish - United States"),
            new DataSourceItem("es-UY", "Spanish - Uruguay"),
            new DataSourceItem("es-VE", "Spanish - Venezuela, Bolivarian Republic of"),
            new DataSourceItem("es-ec", "Spanish - Ecuador"),
            new DataSourceItem("et-EE", "Estonian - Estonia"),
            new DataSourceItem("eu-ES", "Basque - Spain"),
            new DataSourceItem("fas-IR", "Farsi - Iran"),
            new DataSourceItem("fi-FI", "Finnish - Finland"),
            new DataSourceItem("fil-PH", "Filipino - Philippines"),
            new DataSourceItem("fo-FO", "Faroese - Faroe Islands"),
            new DataSourceItem("fr-BE", "French - Belgium"),
            new DataSourceItem("fr-CA", "French - Canada"),
            new DataSourceItem("fr-CH", "French - Switzerland"),
            new DataSourceItem("fr-FR", "French - France"),
            new DataSourceItem("fr-HT", "French - Haiti"),
            new DataSourceItem("fr-LU", "French - Luxembourg"),
            new DataSourceItem("fr-MA", "French - Morocco"),
            new DataSourceItem("fr-MC", "French - Monaco"),
            new DataSourceItem("fr-NL", "French - Netherlands"),
            new DataSourceItem("fr-RE", "French - Reunion"),
            new DataSourceItem("fr-TG", "French - Togo"),
            new DataSourceItem("fr-US", "French - US"),
            new DataSourceItem("fr-XC", "French - International"),
            new DataSourceItem("fy-NL", "Western Frisian - Netherlands"),
            new DataSourceItem("ga-IE", "Irish - Ireland"),
            new DataSourceItem("gd-GB", "Gaelic - United Kingdom"),
            new DataSourceItem("gd-IE", "Gaelic - Ireland"),
            new DataSourceItem("gl-ES", "Galician - Spain"),
            new DataSourceItem("grc-GR", "Ancient Greek"),
            new DataSourceItem("gsw-FR", "Alsatian - France"),
            new DataSourceItem("gu-IN", "Gujarati - India"),
            new DataSourceItem("ha-Latn-NG", "Hausa - Nigeria"),
            new DataSourceItem("hat-HT", "Haitian - Creole"),
            new DataSourceItem("haw-US", "Hawaiian - USA"),
            new DataSourceItem("he-IL", "Hebrew - Israel"),
            new DataSourceItem("her-NA", "Herero - Namibia"),
            new DataSourceItem("hi-IN", "Hindi - India"),
            new DataSourceItem("hil-PH", "Hiligaynon - Phillipine Islands"),
            new DataSourceItem("hmn-CN", "Hmong - China"),
            new DataSourceItem("hmn-US", "Hmong - USA"),
            new DataSourceItem("hmn-VN", "Hmong - Vietnam"),
            new DataSourceItem("hr-HR", "Croatian - Croatia"),
            new DataSourceItem("hu-HU", "Hungarian - Hungary"),
            new DataSourceItem("hy-AM", "Armenian - Armenia"),
            new DataSourceItem("hyw", "Armenian - Western"),
            new DataSourceItem("ia", "Interlingua"),
            new DataSourceItem("id-ID", "Indonesian - Indonesia"),
            new DataSourceItem("ie", "Interlingue"),
            new DataSourceItem("ig-NG", "Igbo - Nigeria"),
            new DataSourceItem("ii-CN", "Nuosu - China"),
            new DataSourceItem("ilo-PH", "Ilocano - Philippines"),
            new DataSourceItem("ipk", "Inupiaq - USA-Canada"),
            new DataSourceItem("is-IS", "Icelandic - Iceland"),
            new DataSourceItem("it-CH", "Italian - Switzerland"),
            new DataSourceItem("it-IT", "Italian - Italy"),
            new DataSourceItem("iu-Cans-CA", "Inuktitut - Canada"),
            new DataSourceItem("iu-Latn-CA", "Inuktitut - Canada"),
            new DataSourceItem("ium", "Iu Mien"),
            new DataSourceItem("ja-IN", "Jantia - India"),
            new DataSourceItem("ja-JP", "Japanese - Japan"),
            new DataSourceItem("jav-ID", "Javanese - Indonesia"),
            new DataSourceItem("ka-GE", "Georgian - Georgia"),
            new DataSourceItem("kh-IN", "Khasi - India"),
            new DataSourceItem("khm-KH", "Cambodian - Cambodia"),
            new DataSourceItem("kk-KZ", "Kazakh - Kazakhstan"),
            new DataSourceItem("kl-GL", "Kalaallisut - Greenland"),
            new DataSourceItem("km-KH", "Khmer - Cambodia"),
            new DataSourceItem("kmr", "Kurdish - Kurmanji"),
            new DataSourceItem("kn-IN", "Kannada - India"),
            new DataSourceItem("ko-IN", "Kokborok - India"),
            new DataSourceItem("ko-KR", "Korean - Korea, Republic of"),
            new DataSourceItem("kok-IN", "Konkani - India"),
            new DataSourceItem("kos-FM", "Kosraean - Micronesia"),
            new DataSourceItem("ks-IN", "Kashmiri - India"),
            new DataSourceItem("ksw-MM", "Karen - Myanmar"),
            new DataSourceItem("kun-ER", "Kunama - Eritrea"),
            new DataSourceItem("kur", "Kurdish - Sorani"),
            new DataSourceItem("ky-KG", "Kyrgyz - Kyrgyzstan"),
            new DataSourceItem("la-Intl", "Latin - International"),
            new DataSourceItem("lb-LU", "Luxembourgish - Luxembourg"),
            new DataSourceItem("lg-UG", "Ganda - Uganda"),
            new DataSourceItem("lmo-IT", "Lombard - Italy"),
            new DataSourceItem("ln-CG", "Lingala - Congo"),
            new DataSourceItem("lo-LA", "Lao - Lao People's Democratic Republic"),
            new DataSourceItem("lt-LT", "Lithuanian - Lithuania"),
            new DataSourceItem("lua-CD", "Luba-Lulua - Congo DRC"),
            new DataSourceItem("lug-UG", "Ganda - Uganda"),
            new DataSourceItem("lv-LV", "Latvian - Latvia"),
            new DataSourceItem("ma-NY", "Many Locales - "),
            new DataSourceItem("mah-MH", "Marshallese - Marshall Islands"),
            new DataSourceItem("mai-IN", "Maithili - India"),
            new DataSourceItem("mfe-MU", "Morisyen - Mauritius"),
            new DataSourceItem("mi-IN", "Mizo - India"),
            new DataSourceItem("mi-NZ", "Māori - New Zealand"),
            new DataSourceItem("mk-MK", "Macedonian - North Macedonia"),
            new DataSourceItem("ml-IN", "Malayalam - India"),
            new DataSourceItem("mlg-MG", "Malagasy - Madagascar"),
            new DataSourceItem("mn-MN", "Mongolian - Mongolia"),
            new DataSourceItem("mn-Mong-CN", "Mongolian - Traditional Mongolian, PRC"),
            new DataSourceItem("mnk-GM", "Mandingo - Gambia"),
            new DataSourceItem("mo-MD", "Moldavian - Moldova"),
            new DataSourceItem("moh-CA", "Mohawk - Mohawk"),
            new DataSourceItem("mr-IN", "Marathi - India"),
            new DataSourceItem("ms-BN", "Malay - Brunei Darussalam"),
            new DataSourceItem("ms-MY", "Malay - Malaysia"),
            new DataSourceItem("ms-SG", "Malay - Singapore"),
            new DataSourceItem("mt-MT", "Maltese - Malta"),
            new DataSourceItem("mya-MM", "Burmese - Myanmar"),
            new DataSourceItem("nb-NO", "Norwegian, Bokm̴l - Norway"),
            new DataSourceItem("nbl-ZW", "Southern Ndebele - Zimbabwe"),
            new DataSourceItem("nde-ZW", "Northern Ndebele - Zimbabwe"),
            new DataSourceItem("ne-NP", "Nepali - Nepal"),
            new DataSourceItem("nl-BE", "Dutch - Belgium"),
            new DataSourceItem("nl-NL", "Dutch - Netherlands"),
            new DataSourceItem("nn-NO", "Norwegian Nynorsk - Norway"),
            new DataSourceItem("nso-ZA", "Northern Sotho - South Africa"),
            new DataSourceItem("nus-Aafr", "Nuer - Africa"),
            new DataSourceItem("nya-MW", "Nyanja - Malawi"),
            new DataSourceItem("oc-FR", "Occitan - France"),
            new DataSourceItem("ogo-NG", "Khana - Nigeria"),
            new DataSourceItem("or-IN", "Oriya - India"),
            new DataSourceItem("orm-ET", "Oromo - Ethiopia"),
            new DataSourceItem("ota-TR", "Ottoman Turkish - Turkey"),
            new DataSourceItem("pa-IN", "Punjabi - India"),
            new DataSourceItem("pa-PK", "Panjabi - Pakistan"),
            new DataSourceItem("pau-PW", "Palauan - Palau"),
            new DataSourceItem("pcm-NG", "Nigerian Pidgin - Nigeria"),
            new DataSourceItem("pl-PL", "Polish - Poland"),
            new DataSourceItem("pon-FM", "Pohnpeian - Micronesia"),
            new DataSourceItem("prs-AF", "Dari - Afghanistan"),
            new DataSourceItem("ps-AF", "Pashto - Afghanistan"),
            new DataSourceItem("ps-PK", "Pashto / Pushto - Pakistan"),
            new DataSourceItem("pt-Afr", "Portuguese - Africa"),
            new DataSourceItem("pt-BR", "Portuguese - Brazil"),
            new DataSourceItem("pt-PT", "Portuguese - Portugal"),
            new DataSourceItem("qut-GT", "K'iche - Guatemala"),
            new DataSourceItem("quz-BO", "Quechua - Bolivia"),
            new DataSourceItem("quz-EC", "Quechua - Ecuador"),
            new DataSourceItem("quz-PE", "Quechua - Peru"),
            new DataSourceItem("qya-LoR", "Quenya - LoR"),
            new DataSourceItem("ra-IN", "Rajasthani - India"),
            new DataSourceItem("rm-CH", "Romansh - Switzerland"),
            new DataSourceItem("rn-BI", "Kirundi - Burundi"),
            new DataSourceItem("ro-RO", "Romanian - Romania"),
            new DataSourceItem("roh-CH", "Rhaeto-Romanic - Swiss"),
            new DataSourceItem("ru-AM", "Russian - Armenia"),
            new DataSourceItem("ru-AZ", "Russian - Azerbaijan"),
            new DataSourceItem("ru-BY", "Russian - Belarus"),
            new DataSourceItem("ru-GE", "Russian - Georgia"),
            new DataSourceItem("ru-MD", "Russian - Moldova, Republic of"),
            new DataSourceItem("ru-RU", "Russian - Russian Federation"),
            new DataSourceItem("ru-UA", "Russian - Ukraine"),
            new DataSourceItem("rw-RW", "Kinyarwanda - Rwanda"),
            new DataSourceItem("sa-IN", "Sanskrit - India"),
            new DataSourceItem("sah-RU", "Yakut - Russia"),
            new DataSourceItem("sg-CF", "Sango - Central African Republic"),
            new DataSourceItem("si-LK", "Sinhala - Sri Lanka"),
            new DataSourceItem("sjn-LoR", "Sindarin - LoR"),
            new DataSourceItem("sk-SK", "Slovak - Slovakia"),
            new DataSourceItem("sl-SI", "Slovene - Slovenia"),
            new DataSourceItem("smn-FI", "Sami - Finland"),
            new DataSourceItem("smo-AS", "Samoan - American Samoa"),
            new DataSourceItem("sna-ZW", "Shona - Zimbabwe"),
            new DataSourceItem("snd-PK", "Sindhi - Pakistan"),
            new DataSourceItem("som-SO", "Somali - Somalia"),
            new DataSourceItem("sot-ZA", "Sesotho - South Africa"),
            new DataSourceItem("sq-AL", "Albanian - Albania"),
            new DataSourceItem("sr-Cyrl-BA", "Serbian - Bosnia and Herzegovina"),
            new DataSourceItem("sr-Cyrl-SP", "Serbian - Serbia"),
            new DataSourceItem("sr-Latin-SP", "Serbian - Serbia"),
            new DataSourceItem("srp-ME", "Montenegrin - Montenegro"),
            new DataSourceItem("ssw-SZ", "Swazi - Swaziland"),
            new DataSourceItem("sun-ID", "Sundanese - Indonesia"),
            new DataSourceItem("sv-FI", "Swedish - Finland"),
            new DataSourceItem("sv-SE", "Swedish - Sweden"),
            new DataSourceItem("sw-KE", "Swahili - Kenya"),
            new DataSourceItem("sw-UG", "Swahili - Uganda"),
            new DataSourceItem("swh-TZ", "Swahili - Tanzania"),
            new DataSourceItem("syl-BD", "Sylheti - Bangladesh"),
            new DataSourceItem("syr-SY", "Syriac - Syria"),
            new DataSourceItem("ta-IN", "Tamil - India"),
            new DataSourceItem("te-IN", "Telugu - India"),
            new DataSourceItem("tet-ID", "Tetum - Indonesia"),
            new DataSourceItem("tet-TL", "Tetum - Timor-Leste"),
            new DataSourceItem("tg-Cyrl-TJ", "Tajik - Tajikistan"),
            new DataSourceItem("tgl-PH", "Tagalog - Philippines"),
            new DataSourceItem("tgl-US", "Taglish - "),
            new DataSourceItem("th-TH", "Thai - Thailand"),
            new DataSourceItem("tir-ET", "Tigrinya - Ethiopia"),
            new DataSourceItem("tk-TM", "Turkmen - Turkmenistan"),
            new DataSourceItem("tmz-Latn-DZ", "Tamazight - Algeria"),
            new DataSourceItem("tn-ZA", "Tswana - South Africa"),
            new DataSourceItem("tnz-TH", "Tonga - Thailand"),
            new DataSourceItem("to-TO", "Tonga - Tonga"),
            new DataSourceItem("tr-TR", "Turkish - Turkey"),
            new DataSourceItem("tt-RU", "Tatar - Russian Federation"),
            new DataSourceItem("twi-GH", "Twi - Ghana"),
            new DataSourceItem("ug-CN", "Uyghur - China"),
            new DataSourceItem("uk-UA", "Ukrainian - Ukraine"),
            new DataSourceItem("ur-IN", "Urdu - India"),
            new DataSourceItem("ur-PK", "Urdu - Pakistan"),
            new DataSourceItem("uz-AF", "Uzbek - Afghanistan"),
            new DataSourceItem("uz-Cyrl-UZ", "Uzbek - Uzbekistan"),
            new DataSourceItem("uz-Latn-UZ", "Uzbek - Uzbekistan"),
            new DataSourceItem("vi-VN", "Vietnamese - Viet Nam"),
            new DataSourceItem("vls-NL", "Flemish - Netherlands"),
            new DataSourceItem("vo", "Volapük"),
            new DataSourceItem("vo-DE", "Volapuek - Germany"),
            new DataSourceItem("wee-DE", "Lower Sorbian - Germany"),
            new DataSourceItem("wen-DE", "Upper Sorbian - Germany"),
            new DataSourceItem("wo-SN", "Wolof - Senegal"),
            new DataSourceItem("xh-ZA", "Xhosa - South Africa"),
            new DataSourceItem("xsm-GH", "Kasem - Ghana"),
            new DataSourceItem("yap-FM", "Yapese - Micronesia"),
            new DataSourceItem("ydd-IL", "Yiddish - Israel"),
            new DataSourceItem("yo-NG", "Yoruba - Nigeria"),
            new DataSourceItem("yue-CN", "Chinese - Yue Cantonese"),
            new DataSourceItem("yue-HK", "Cantonese - Hong Kong"),
            new DataSourceItem("zh-HK", "Chinese - Hong Kong"),
            new DataSourceItem("zh-Hans", "Chinese - Mainland China"),
            new DataSourceItem("zh-Hant", "Chinese - Taiwan"),
            new DataSourceItem("zh-MO", "Chinese - Macao"),
            new DataSourceItem("zh-SG", "Chinese - Singapore"),
            new DataSourceItem("zh-US", "Chinese - Traditional US"),
            new DataSourceItem("zh-XC", "Chinese - International"),
            new DataSourceItem("zul-ZA", "Zulu - South Africa")
        };
    }
}
